DROP TABLE IF EXISTS FAMILY_MEMBER;  
CREATE TABLE FAMILY_MEMBER (  
id VARCHAR(50) PRIMARY KEY,  
name VARCHAR(100) NOT NULL  
);

DROP TABLE IF EXISTS GIFT_EXCHANGE;  
CREATE TABLE GIFT_EXCHANGE (  
member_id VARCHAR(50) PRIMARY KEY,  
recipient_member_id VARCHAR(100) NOT NULL  
);

